### PR TITLE
General code improvements

### PR DESCRIPTION
**Pull request by saharNooby**
No new features here.

Possible bugfix from aligning case insensitive comparison behavior with `String.compareToIgnoreCase`.

May need to bump patch version, but see #6

### CODE REVIEW

**Comment by saharNooby** [comment]
Version change not needed as indicated in #6

**Comment by jagobagascon** [comment]
I would prefer to have smaller pull-request (with a single commit if possible), I takes a little bit extra work but I'm not a big fan of adding so many different things into a single PR.

I might be fine with some of your changes and not so much with others and also it makes it harder to review / request changes. So let's keep the pull requests relevant, with a small description of what and why is being changed.

**Sorry I didn't make it clear in your first PR**.

That said:
- **I like the case insensitive comparison fix**, even though it only applies to the Georgian alphabet, it is still a bug, so good catch! **Could you do that in another separate pull request?** Maybe even include a test with Georgian characters to test that the bug happens and validate the applied fix?
- The javadoc improvement is OK, but again, in a different PR.
- About the typos, I don't think there's anything wrong with using a lower case comment.
- And about the changes made to the tests, I'm not a big fan of having randomness in them. I'm not sure why I did that but I think it is a bad idea. Increasing the amount of times the tests are run might make them more deterministic, but I would completely get rid of that randomness. If you want to propose a solution in another pull request I might consider it, otherwise I will revisit the tests in the future.

**Comment by saharNooby** [comment]
>I would prefer to have smaller pull-request

I'll try to split this PR then, although not sure how to do it for now. I'll do it when I have time.

>Maybe even include a test with Georgian characters to test that the bug happens and validate the applied fix?

Adding test to check that code after change behaves correctly sounds great, I will add a test case (if possible, of course, I'm not familiar with Georginan alphabet).

>About the typos, I don't think there's anything wrong with using a lower case comment.

It's about consistency -- in main method comments start with upper case letter, so I changed other comments to match them. Of course comments starting with lower case are fine, but if you prefer this way -- all other comments also should start with lower case letters. I'm assuming that consistency matters here.

>And about the changes made to the tests, I'm not a big fan of having randomness in them.

I would argue that randomized testing with many passes greatly increases test power, because there are significantly more string-to-string combinations tested than when using a single example. To remove randomness and retain that power, one would need to include tens or hundreds lines of code with all possible examples. Of course these test cases can be generated (using the same code).

>Increasing the amount of times the tests are run might make them more deterministic

"Deterministic" in my code comment means "string order does not change from launch to launch, so test behavior does not change with time and between different machines". Run count does not affect determinity, fixed seed does.

Anyway, final decision is yours, if I did not convince you that a little randomness is good -- I will not include this commit in next PRs.

**Comment by jagobagascon** [comment]
> I would argue that randomized testing with many passes greatly increases test power, because there are significantly more string-to-string combinations tested than when using a single example. To remove randomness and retain that power, one would need to include tens or hundreds lines of code with all possible examples. Of course these test cases can be generated (using the same code).

> "Deterministic" in my code comment means "string order does not change from launch to launch, so test behavior does not change with time and between different machines". Run count does not affect determinity, fixed seed does.

Ok, my fault, I didn't properly check the changes made to the random seed. Now I'm liking your change a liitle bit more 😄 .

> I'll try to split this PR then, although not sure how to do it for now. I'll do it when I have time.

Thanks a lot!

**Comment by saharNooby** [comment]
Hello again, there are 9 commits, it would be too cumbersome to create a separate branch for each commit and either rollback all unneeded commits in the branch or make changes manually.

Since you (as I understood) now approve all changes, can I add case-insensitive comparison test case as extra commit to this PR, and then you reopen and merge it?

If you would prefer some changes be rolled back, please tell explicitly.

Of course future PRs will be correctly split.

**Comment by jagobagascon** [comment]
I guess I can do an exception.

**Pull request merged**
